### ISSUE TITLE
Update the CONTRIBUTION.md file name to CONTRIBUTING.md and update the contents to mention the issues page and the repo's current project page.

### ISSUE THREAD

**Issue by osioke** [devcenter-square/disease-info#30]
Update the CONTRIBUTION.md file name to CONTRIBUTING.md so as to allow GitHub direct new repo visitors to this guide.

And update the contents to mention or talk about the issues page so willing contributors know to check there, and the current repo project page, so they know what project the repo is currently undergoing, and the available TODOs.

**Comment by ruqoyyasadiq** [comment]
@osioke has this been worked on yet? I would want to work on it.

**Comment by osioke** [comment]
Thank you @andela-rsadiq 👍
