### ISSUE TITLE
low code test coverage.

### ISSUE THREAD

**Issue by SquareDC** [devcenter-square/disease-info#42]
We need to bring up test coverage to > 90% . Currently, what we have and where we are lagging is as can be seen in the attached.

<img width="671" alt="screen shot 2016-10-20 at 8 08 14 am" src="https://cloud.githubusercontent.com/assets/22894076/19549531/bab76260-969c-11e6-9eb3-a960fbbbb43e.png">

**Comment by luizvarela** [comment]
I think we can close this issue.

**Comment by AfolabiOlaoluwa** [comment]
Yes

**Comment by x6iae** [comment]
This is totally done now... we rolling at 100%
